NEI <- readRDS("summarySCC_PM25.rds")
SCC <- readRDS("Source_Classification_Code.rds")
Emissions <- tapply(NEI$Emissions, NEI$year, sum)
png("plot1.png")
barplot(Emissions/1000000, xlab="Year", ylab="PM2.5 Emissions (Million Tons)", main="Total PM2.5 Emissions in US by Year", ylim=c(0,8))
dev.off()
